### ISSUE TITLE
[10.0] odoo.conf: credit-control

### ISSUE THREAD

**Issue by vpcarlos** [Aselcis-Consulting/asoo-odoo#1]
Al desplegar un entorno de Odoo v10 da error debido a que el submódulo credit-control todavía sigue en el addons path.
https://github.com/Aselcis-Consulting/asoo-odoo/blob/85795fefc3fd112e2b191923f1ce940bf15a44f2/config/odoo.conf#L4

**Comment by jvargass** [comment]
Arreglado en 10.0 y 10.0-enterprise.
